### ISSUE TITLE
Add a license please

### ISSUE THREAD

**Issue by Zimmi48** [kurtharriger/elm-battleship#1]
Hello,

Thanks a lot for your helpful native JS library for drag and drop.
Maybe it would make sense to package it as a real library to distribute on Elm package site.
In the meantime, I would appreciate if you could add a license to this repository (or just to the header of Native/DragDrop.js) : thus I would feel more legitimate to re-use it in my own logic game https://github.com/Zimmi48/logicgame.
Finally let me add that my only reason to go native was to make my game work on Firefox. For whatever reason they require a call to dataTransfer.setData so that dragging works, so I had to add the following line in your JS code:
`// This stupid setData call is necessary to make drag and drop work on FF
event.dataTransfer.setData("text","");`

Thanks,
Théo

**Comment by kurtharriger** [comment]
Glad you found it useful.  Updated project with a very liberal license.

**Comment by Zimmi48** [comment]
Thanks! Great choice ;)
